### ISSUE TITLE
Export HTML not updated

### ISSUE THREAD

**Issue by dirtymurdoc** [unlayer/react-email-editor#63]
**Environment**
- FF 67.0b2
- MacOS 10.14.3

**Test case**
- Open console
- Add a button to canvas
- Rename button "click"
- Click on "Export HTML" button directly w/o clicking on editor canvas

**Expected Behavior** 
- Output HTML for button is "click"

**Actual behvior**
- Output HTML for button is "Button Text"

**Reproduction link**
- https://codesandbox.io/s/ojr04wo6wy

**Comment by adeelraza** [comment]
@dirtymurdoc this issue should be resolved. Can you try again?

**Comment by dirtymurdoc** [comment]
@adeelraza Thanks for you reply. The problem describe above is fixed but the update have side effets.
The application crash when editing a button.

See https://codesandbox.io/s/p9x6nkoqyj?fontsize=14

It was totally ok before the update.

**Comment by adeelraza** [comment]
@dirtymurdoc can you clear cache and try again? We have deployed a potential fix for this.

**Comment by dirtymurdoc** [comment]
Hi @adeelraza and thank you for you support but it still NOT ok.
I have updated the codesanbox (https://codesandbox.io/s/o4np6ov42z) and the `design:updated` event is now always triggered.

See https://codesandbox.io/s/o4np6ov42z
Open console
Add a button
Edit button
And you will see all the "design:updated" log

**Comment by lidrissi** [comment]
I encounter the same issue, and it still not ok

**Comment by adeelraza** [comment]
@dirtymurdoc can you check again? This was triggered by a case where `exportHtml` is called inside `design:updated` event. We have deployed a fix for this.

**Comment by dirtymurdoc** [comment]
Thank you @adeelraza. That's OK for me.
